In [1]:
import cv2
import numpy as np
import torch
# from google.colab.patches import cv2_imshow

In [3]:
def load_image_and_convert_to_tensor(image_path, target_size=(30, 30)):
    # Load the image using OpenCV
    image = cv2.imread(image_path)
    # Display the image in a window
    # cv2_imshow(image)
    # cv2.imshow("Image", image)

    # Wait for a key press and then close the window
    # cv2.waitKey(0)
    # cv2.destroyAllWindows()

    if image is None:
        # If no image is loaded, return a tensor with 0
        print('Images is None!')
        return np.zeros(target_size, dtype=np.uint8)

    # Resize the image to the target size
    image = cv2.resize(image, target_size)
    # print('image: ', image)
    # Convert the image to grayscale if it's not already
    if len(image.shape) == 3 and image.shape[2] == 3:
        print('It is a 3D image, converting to black and white!')
        image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Convert the grayscale image to a binary tensor
    # binary_tensor = (image > 0).astype(np.uint8)
    binary_tensor = (image < 1).astype(np.uint8)

    return binary_tensor

# Example usage:
image_path = "apple2.jpg"
result = load_image_and_convert_to_tensor(image_path)
print(result)


It is a 3D image, converting to black and white!
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 

---

In [11]:
import torch

# Define the input 2D tensor
input_tensor = torch.tensor([[1, 2, 3],
                             [4, 5, 6],
                             [7, 8, 9]])

# Get the number of rows and columns in the tensor
num_rows, num_cols = input_tensor.shape

# Create an empty list to store the elements in the desired order
result_list = []

# Iterate through the columns in reverse order
for j in range(num_cols - 1, -1, -1):
    # Iterate through the rows in reverse order
    for i in range(num_rows - 1, -1, -1):
        # Append the element to the result list
        result_list.append(input_tensor[i, j])

# Iterate through the columns in reverse order
for j in range(num_cols - 1, -1, -1):
    # Iterate through the rows in reverse order
    for i in range(num_rows - 1, -1, -1):
        # Append the element to the result list
        result_list.append(input_tensor[i, j])

# Convert the result list to a 1D tensor
result_tensor = torch.tensor(result_list)

# Print the result
print(result_tensor)


tensor([9, 6, 3, 8, 5, 2, 7, 4, 1])


In [ ]:
0: tensor([7, 8, 9, 4, 5, 6, 1, 2, 3])
1: tensor([3, 2, 1, 6, 5, 4, 9, 8, 7])

In [22]:
import torch

# Define the input 2D tensor
input_tensor = torch.tensor([[1, 2, 3],
                             [4, 5, 6],
                             [7, 8, 9]])

# Reverse the rows
reversed_tensor = torch.flip(input_tensor, [0])
print(reversed_tensor)

reversed_tensor = torch.transpose(reversed_tensor, 0, 1)
print(reversed_tensor)
# Flatten the reversed tensor
result_tensor = reversed_tensor.reshape(-1)

# Print the result
print(result_tensor)


tensor([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]])
tensor([[7, 4, 1],
        [8, 5, 2],
        [9, 6, 3]])
tensor([7, 4, 1, 8, 5, 2, 9, 6, 3])


In [ ]:
import torch

# Define the input 2D tensor
input_tensor = torch.tensor([[1, 2, 3],
                             [4, 5, 6],
                             [7, 8, 9]])

# Reverse the rows
reversed_tensor = torch.flip(input_tensor, [0])
print(reversed_tensor)
transposed_tensor = reversed_tensor.t()
print(transposed_tensor)
# Flatten the reversed tensor
result_tensor = transposed_tensor.view(-1)

# Print the result
print(result_tensor)


---

In [1]:
print("Hello World")

Hello World


In [2]:
# Load the black and white image
image_path = './duck.jpg'  # Replace with your image path
image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

# Resize the image to 400x500
desired_size = (64, 64)
resized_image = cv2.resize(image, desired_size, interpolation=cv2.INTER_AREA)

# Apply thresholding to create a binary image
_, binary_image = cv2.threshold(resized_image, 127, 255, cv2.THRESH_BINARY_INV)

# Convert binary image to binary tensor
binary_tensor = torch.tensor(binary_image, dtype=torch.float32) / 255.0

# Display the original and resized images
cv2.imshow('Original Image', image)
cv2.imshow('Resized and Binary Image', binary_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: name 'cv2' is not defined

In [ ]:
import numpy as np
import torch
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [ ]:
def rotate_xyz(p, angles):
    '''
    Reference: http://www.songho.ca/opengl/gl_anglestoaxes.html
    '''
    θx, θy, θz = angles
    θx = torch.FloatTensor([θx * 3.14159 / 180.0])
    θy = torch.FloatTensor([θy * 3.14159 / 180.0])
    θz = torch.FloatTensor([θz * 3.14159 / 180.0])
    R_zyx = torch.tensor([ 
        [torch.cos(θz)*torch.cos(θy), -torch.sin(θz)*torch.cos(θx) + torch.cos(θz)*torch.sin(θy)*torch.sin(θx), torch.sin(θz)*torch.sin(θx)+torch.cos(θz)*torch.sin(θy)*torch.cos(θx)],
        [torch.sin(θz)*torch.cos(θy), torch.cos(θz)*torch.cos(θx)+torch.sin(θz)*torch.sin(θy)*torch.sin(θx), -torch.cos(θz)*torch.sin(θx)+torch.sin(θz)*torch.sin(θy)*torch.cos(θx)],
        [-torch.sin(θy), torch.cos(θy)*torch.sin(θx), torch.cos(θy)*torch.cos(θx)]
    ])
    p = p.float()
    R_zyx = R_zyx.float()
    return torch.matmul(p, R_zyx.T)

In [ ]:
def sdf_sphere(p, r, center, angles):
    p_rotated = rotate_xyz(p, angles)
    return torch.sqrt(torch.sum((p_rotated - center)**2, dim=1)) - r

In [ ]:
def sdBox(p, b, center, angles):
    '''
    p = point to be tested, nx3 tensor
    b = half the length of box, i.e. coordinates of the corner from the center
    center = center of the box
    angles = rotation angles in degrees
    '''
    p_rotated = rotate_xyz(p, angles)
    q = torch.abs(p_rotated-center) - b
    return torch.norm(torch.max(q, torch.tensor([0.,0.,0.])), dim=1) + torch.min(torch.max(q, dim=1)[0], torch.tensor([0.]))

In [ ]:
# Create a grid of points in 3D space
x = np.linspace(-5, 5, 50)
y = np.linspace(-5, 5, 50)
z = np.linspace(-5, 5, 50)
X, Y, Z = np.meshgrid(x, y, z)
points = np.stack((X, Y, Z), axis=-1).reshape(-1, 3)

# Calculate the signed distance function for a sphere and a box
sphere_sdf = sdf_sphere(torch.tensor(points), r=2.0, center=torch.tensor([0.0, 0.0, 0.0]), angles=torch.tensor([0.0, 0.0, 0.0]))
box_sdf = sdBox(torch.tensor(points), b=torch.tensor([1.0, 1.0, 1.0]), center=torch.tensor([0.0, 0.0, 0.0]), angles=torch.tensor([0.0, 0.0, 0.0]))

# Reshape the signed distance values to match the grid shape
sphere_sdf = sphere_sdf.reshape(50, 50, 50)
box_sdf = box_sdf.reshape(50, 50, 50)

# Create a 3D plot
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Plot the surfaces using contour plots
ax.contourf(X, Y, Z, sphere_sdf, cmap='viridis', alpha=0.5)
ax.contourf(X, Y, Z, box_sdf, cmap='plasma', alpha=0.5)

# Set labels and title
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
ax.set_title('Signed Distance Function Visualization')

plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Define the parameters to visualize
param1_values = np.linspace(-5, 5, 100)
param2_values = np.linspace(-5, 5, 100)

# Create a grid of parameter values
param1_grid, param2_grid = np.meshgrid(param1_values, param2_values)

# Calculate the loss for each parameter combination (simplified example)
def loss_function(param1, param2):
    return param1 ** 2 + param2 ** 2

loss_grid = loss_function(param1_grid, param2_grid)

# Create a contour plot of the loss landscape
plt.contourf(param1_grid, param2_grid, loss_grid, levels=20, cmap="viridis")
plt.colorbar()

# Simulate optimization trajectory (simplified example)
trajectory_param1 = np.array([-4, -3, -2, -1, 0, 1, 2, 3, 4])
trajectory_param2 = np.array([3, 2, 1, 0, -1, -2, -3, -4, -5])

plt.plot(trajectory_param1, trajectory_param2, marker="o", color="red")

plt.xlabel("Parameter 1")
plt.ylabel("Parameter 2")
plt.title("Loss Landscape and Optimization Trajectory")

plt.show()


In [ ]:
loss_grid